name: Dependency Vulnerability Scan

on:
  push:
    branches: [main]
  pull_request:

jobs:
  dependency-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install OWASP Dependency-Check
        run: |
          wget https://github.com/jeremylong/DependencyCheck/releases/download/v8.4.0/dependency-check-8.4.0-release.zip
          unzip dependency-check-8.4.0-release.zip -d $HOME/dependency-check
          echo "$HOME/dependency-check/dependency-check/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: npm install

      - name: Run Dependency-Check
        run: |
          dependency-check.sh \
            --project "implantweb" \
            --scan . \
            --format "HTML" \
            --out dependency-check-report \
            --disableAssembly || true

      - name: Upload Dependency-Check Report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: dependency-check-report
