name: CI

on:
  push:
    branches:
      - main  # This will trigger the workflow on every push to the main branch
    paths-ignore:
      - .github/workflows/cicd-ecs.yml
      - .github/workflows/ci.yml
      - Dockerfile

  pull_request:
    branches:
      - main  # This will trigger the workflow for pull requests targeting the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Grant execute permission
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: |
          ./gradlew build
          ./gradlew bootJar

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-app-artifact
          path: build/libs/*.jar
